runtime: python
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"
    
env: standard
instance_class: F1
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.384
  disk_size_gb: 10